// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!

import { Outlet } from 'umi';

export default function Layout() {
  return (
    <div>
      {/*全局面包屑*/}
      {/*生成一个好看的底部div*/}
      <Outlet />
    </div>
  );
}
