// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!

import { Outlet } from 'umi';

export default function Layout() {
  return (
    <div>
      <div style={{ height: '300px', width: '300px', backgroundColor: 'yellow' }}></div>
      <Outlet />
    </div>
  );
}
