// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { Outlet } from 'umi';

export default function Layout() {
  return (
    <div>
      <div>hello</div>
      <Outlet />
    </div>
  );
}
